replicaCount: 1

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: simple-web

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: simple-web
  contextPath: /evgeny
  annotations: {}

ingress:
  enabled: true
  path: /evgeny
  labels: {}
  tls: []

resources:
  limits:
    cpu: 1m
    memory: 1024Mi
  requests:
    cpu: 1m
    memory: 1024Mi

keda:
  enabled: true
  maxReplicaCount: 5
  triggers:
    cpu:
      percent: 50
    memory:
      percent: 50
    cron:
      timezone: Asia/Jerusalem
      start: 0 8 * * *
      end: 0 0 * * *

autoscaling: {}

nodeSelector: {}

affinity: {}