{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include " simple-web.fullname" . }}
  labels:
    {{- include " simple-web.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include " simple-web.fullname" . }}
  minReplicaCount: {{ .Values.replicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: {{ .Values.keda.triggers.cpu.percent | quote }}
  - type: memory
    metadata:
      type: Utilization
      value: {{ .Values.keda.triggers.memory.percent | quote }}
- type: cron
  metadata:
    timezone: Asia/Jerusalem
    start: 30 * * * *
    end: 45 * * * *
    desiredReplicas: {{ .Values.keda.maxReplicaCount | quote }}
{{- end }}